/* eslint-disable */
// This file was autogenerated by convex.
// Run `npx convex dev --once` to regenerate it.

import type { FunctionReference } from "convex/server";

export const api = {
  auth: {
    createUser: {
      args: { email: "string", name: "string?", avatar: "string?", googleId: "string" },
      returns: "id",
    } as FunctionReference<"mutation", "public", "auth", {
      email: string;
      name?: string;
      avatar?: string;
      googleId: string;
    }, string>,
    getUserByGoogleId: {
      args: { googleId: "string" },
      returns: "object | null",
    } as FunctionReference<"query", "public", "auth", {
      googleId: string;
    }, any | null>,
    getUserById: {
      args: { userId: "id" },
      returns: "object | null",
    } as FunctionReference<"query", "public", "auth", {
      userId: any;
    }, any | null>,
    createSession: {
      args: { userId: "id", token: "string" },
      returns: "id",
    } as FunctionReference<"mutation", "public", "auth", {
      userId: any;
      token: string;
    }, any>,
    validateSession: {
      args: { token: "string" },
      returns: "object | null",
    } as FunctionReference<"query", "public", "auth", {
      token: string;
    }, any | null>,
    logout: {
      args: { token: "string" },
      returns: "boolean",
    } as FunctionReference<"mutation", "public", "auth", {
      token: string;
    }, boolean>,
  },
} as const;