/* eslint-disable */
// This file was autogenerated by convex.
// Run `npx convex dev --once` to regenerate it.

import type { FunctionReference } from "convex/server";

export const api = {
  auth: {
    registerUser: {
      args: { email: "string", password: "string", name: "string?" },
      returns: "id",
    } as FunctionReference<"mutation", "public", "auth", {
      email: string;
      password: string;
      name?: string;
    }, string>,
    loginUser: {
      args: { email: "string", password: "string" },
      returns: "id",
    } as FunctionReference<"mutation", "public", "auth", {
      email: string;
      password: string;
    }, string>,
    getUserById: {
      args: { userId: "id" },
      returns: "object | null",
    } as FunctionReference<"query", "public", "auth", {
      userId: any;
    }, any | null>,
    createSession: {
      args: { userId: "id", token: "string" },
      returns: "id",
    } as FunctionReference<"mutation", "public", "auth", {
      userId: any;
      token: string;
    }, any>,
    validateSession: {
      args: { token: "string" },
      returns: "object | null",
    } as FunctionReference<"query", "public", "auth", {
      token: string;
    }, any | null>,
    logout: {
      args: { token: "string" },
      returns: "boolean",
    } as FunctionReference<"mutation", "public", "auth", {
      token: string;
    }, boolean>,
  },
} as const;