/* eslint-disable */
// This file was autogenerated by convex.
// Run `npx convex dev --once` to regenerate it.

export type DataModel = {
  users: {
    _id: any;
    _creationTime: number;
    email: string;
    name?: string;
    avatar?: string;
    googleId: string;
    createdAt: number;
    lastLogin: number;
    role?: string;
    preferences?: any;
  };
  sessions: {
    _id: any;
    _creationTime: number;
    userId: any;
    token: string;
    expiresAt: number;
    createdAt: number;
  };
};

export type MutationBuilder = any;
export type QueryBuilder = any;